"""Render a Markdown include from docs/_static/native-stress-demo.json."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--json-input",
        type=Path,
        default=Path(__file__).resolve().parent / "_static" / "native-stress-demo.json",
        help="Path to the generated native stress benchmark JSON file.",
    )
    parser.add_argument(
        "--markdown-output",
        type=Path,
        default=(
            Path(__file__).resolve().parent / "_generated" / "native-stress-demo.mdinc"
        ),
        help="Path for the generated Markdown include.",
    )
    return parser.parse_args()


def _format_timestamp(timestamp: str) -> str:
    return (
        datetime.fromisoformat(timestamp)
        .astimezone(timezone.utc)
        .strftime("%Y-%m-%d %H:%M UTC")
    )


def _format_seconds(value: float) -> str:
    return f"{value:.6f} s"


def _format_speedup(value: float) -> str:
    return f"{value:.2f}x"


def render_markdown(payload: dict) -> str:
    generated_label = _format_timestamp(payload["generated_at"])
    results = payload["results"]
    result_by_key = {result["key"]: result for result in results}

    lines = [
        "<!-- Generated by docs/render_native_stress_demo_include.py. Do not edit manually. -->",
        "",
        (
            "Latest machine-specific data was read from "
            "`docs/_static/native-stress-demo.json` "
            f"generated at `{generated_label}`."
        ),
        "",
        "The machine-specific headline from this run is straightforward:",
        "",
        (
            "- native `optv` is dramatically faster for the heaviest matching "
            "workload "
            f"(`Stereo matching`, about `{_format_speedup(result_by_key['stereomatching']['speedup'])}`)"
        ),
        (
            "- preprocessing also shows a large native win "
            f"(`{_format_speedup(result_by_key['preprocess']['speedup'])}`)"
        ),
        (
            "- reconstruction already benefits substantially from the compiled "
            "Python path, so the additional native gain there is smaller "
            f"(`{_format_speedup(result_by_key['reconstruction']['speedup'])}` "
            f"and `{_format_speedup(result_by_key['multilayer_reconstruction']['speedup'])}`)"
        ),
        (
            "- tracking still benefits materially from native execution "
            f"(`{_format_speedup(result_by_key['tracking']['speedup'])}`)"
        ),
        "",
        "| Workload | Python or routed Python path | Native path | Native speedup |",
        "| --- | ---: | ---: | ---: |",
    ]

    for result in results:
        lines.append(
            "| "
            f"{result['label']} | "
            f"{_format_seconds(result['python_seconds'])} | "
            f"{_format_seconds(result['native_seconds'])} | "
            f"{_format_speedup(result['speedup'])} |"
        )

    compiled_results = [
        result for result in results if result.get("compiled_vs_legacy") is not None
    ]
    if compiled_results:
        lines.extend(
            [
                "",
                "For the reconstruction workloads, the same stress test also reported",
                "the benefit of the current compiled Python path over the older",
                "per-point Python loop:",
                "",
            ]
        )
        for result in compiled_results:
            lines.append(
                f"- {result['label'].lower()}: compiled Python was "
                f"{_format_speedup(result['compiled_vs_legacy'])} faster than legacy Python"
            )

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    payload = json.loads(args.json_input.read_text(encoding="utf-8"))
    args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_output.write_text(render_markdown(payload), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
